name: NUtils
version: '${project.version}'
main: ga.nekozouneko.plugins.utils.nutils.NUtils
api-version: 1.17
authors: [ NekozounekoTEAM, Taitaitatata ]
description: "NUtils is Server Utils Tool"
commands:
  nickname:
    description: set your nickname
    permission: NUtils.commands.nickname
    permission-message: "ERROR: CANT RUN nickname command (You dont have perms)"
    usage: "/nickname <Name : String>"
  nfly:
    description: set your nickname
    permission: NUtils.commands.fly
    permission-message: "ERROR: CANT RUN fly command (You dont have perms)"
    usage: /nfly
  gamemode:
    description: Change Gamemode
    permission: NUtils.commands.gamemode
    permission-message: "ยง4I'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."
    usage: "/gamemode <Gamemode> [<target>]"